### ISSUE TITLE
Has this stopped working?

### ISSUE THREAD

**Issue by dinkybluebug** [jonathan-fielding/yalealarmsystem#4]
As of this week, this doesnt work anymore

my node .js file runs, with no errors, but it doesnt do anything anymore

const { getSessionCookie, getStatus, setStatus } = require('yalealarmsystem');
getSessionCookie('username', 'password').then((sessionCookie) => {
    setStatus(sessionCookie, 'home');
});

Anyone else?

**Comment by jak1502** [comment]
I have updated the code now, and added a pull request. You can try it out if you want:

https://github.com/jak1502/yalealarmsystem

**Comment by dinkybluebug** [comment]
How did you know to update this? There isn’t a published API for this is there?

Many thanks

Marc

**Comment by dinkybluebug** [comment]
> I have updated the code now, and added a pull request. You can try it out if you want:
> 
> https://github.com/jak1502/yalealarmsystem
@jak1502 
How did you know to update this? There isn’t a published API for this is there?

Many thanks

Marc

**Comment by dinkybluebug** [comment]
@jak1502  :How did you know to update this? There isn’t a published API for this is there?

Many thanks

Marc

**Comment by jak1502** [comment]
There isn’t a published api no, had to reverse engineer it from the app requests.

**Comment by jak1502** [comment]
I have published this on GitHub at https://github.com/jak1502/yalealarm and on npm as yalealarm as the pull request is still outstanding.

**Comment by jonathan-fielding** [comment]
I have replied to your pr with a change so we can get it merged,

**Comment by jonathan-fielding** [comment]
This is now fixed
